## Set the API endpoint used to create the Service resource.
apiVersion: v1

kind: Service

metadata:
  labels:
    app: tech-trends
  name: tech-trends
  namespace: sandbox
  
spec:

  ports:
  - port: 4111
    protocol: TCP
    targetPort: 4111
  selector:
    app: tech-trends
    
  type: ClusterIP